# Generated by Django 5.2.12 on 2026-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'key'],
                'unique_together': {('page', 'key')},
            },
        ),
    ]
