# Generated by Django 5.2.12 on 2026-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('accent_color', models.CharField(default='#C8FF00', max_length=20)),
                ('url', models.URLField(blank=True, default='')),
                ('has_cover', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cases/covers/')),
                ('brief_headline', models.CharField(blank=True, default='', max_length=500)),
                ('brief_body', models.TextField(blank=True, default='')),
                ('approach_headline', models.CharField(blank=True, default='', max_length=500)),
                ('approach_body', models.TextField(blank=True, default='')),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('scope', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('testimonial_quote', models.TextField(blank=True, default='')),
                ('testimonial_author', models.CharField(blank=True, default='', max_length=200)),
                ('testimonial_role', models.CharField(blank=True, default='', max_length=200)),
                ('highlights', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
    ]
