# Generated by Django 5.2.12 on 2026-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('package', models.CharField(choices=[('essential', 'Essential'), ('studio', 'Studio'), ('brand_plus', 'Brand+'), ('unsure', 'Not sure yet')], default='unsure', max_length=20)),
                ('brief', models.TextField()),
                ('source', models.CharField(choices=[('google', 'Google'), ('referral', 'Referral'), ('social', 'Social Media'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
